name: CI 8-stream


on:
  push:
    tags:
      - '*'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install qemu-utils

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          chmod +x ./build.sh
          ./build.sh
      - name: Release
        uses: actions/upload-artifact@v4
        with:
         name: centos-8-stream
         path: ./wsl/dist/*.zip 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
